# Generated by Django 6.0.4 on 2026-05-08 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_product_cateory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cateory',
            new_name='category',
        ),
    ]
